# Generated by Django 4.1.7 on 2023-05-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
